# Generated by Django 5.1.7 on 2025-03-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.UUIDField(blank=True, default=None, null=True, unique=True)),
                ('email', models.CharField(default=None, max_length=30)),
                ('username', models.CharField(default=None, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
